sudo: required
dist: xenial

language: node_js
node_js: "lts/*"

#apt:
#  sources:
#  - google-chrome
#  packages:
#  - google-chrome-stable
#  - google-chrome-beta
addons:
  chrome: stable

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm run lint
- npm test
- npm run e2e

after_success:
- npm run build

deploy:
- provider: script
  skip_cleanup: true
  script:
    npm run deploy -- --token=$FIREBASE_KEY
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script:
    npm run build -- --configuration=arhs && npm run deploy -- --token=$FIREBASE_KEY -P arhs-bookmarks
  on:
    branch: master
